export interface LineChartsData{
    id: string,
    jan: number,
    feb: number,
    mar: number,
    apr: number,
    may: number,
    jun: number,
    jul: number,
    aug: number,
    sep: number,
    nov: number,
    oct: number,
    dec: number,
}